### ISSUE TITLE
Buggy signup

### ISSUE THREAD

**Issue by upayanmazumder** [kspcommunity/kspcommunity.com#49]
Frontend side: 
`
Signup submitted successfully: {
  authenticated: false,
  email: false,
  error: 'Email and password are required.'
}
`
Backend side: 
` 2024-06-07T07:04:26.196Z [error]: Email and password are required.`

**Comment by upayanmazumder** [comment]
The issue occurs on first attempt at signup and ends up asking for email and password. Consecutive attempts work as they should respectively. Clearing cache/attempting after sometime again brings this error!

**Comment by Larssies** [comment]
for example

```JS
fetch('kspcommunity.com/api/signup', {
  headers: {
   'Content-Type': 'application/json'
  },
 body: JSON.stringify({
  email: 'test@test.com',
  password: 'test'
 })
}
.then(response => response.json())
.then(data => {
 console.log(data)
}
```

**Comment by Larssies** [comment]
The issue sits here

```JS
        body: JSON.stringify({
          username: username.value,
          email: email.value,
          password: password.value,
        }),
```

There is no field for username. So when the body gets sent to the server using a POST request it doesnt recognize the username field and therefore return an error. I am only using an email and password to login!

**Comment by dave9123** [comment]
I fixed the bug, I will probably add username as well and store it at Firestore

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by upayanmazumder** [comment]
Its fixed i believe..

**Comment by Larssies** [comment]
It is not fixed, cookies have not been synced with the main domain name yet. So it currently does not work.
